<a href="https://colab.research.google.com/github/kaamiawan007/pytorch/blob/main/Arithematic_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Arithematic Opertions**

In [1]:
import numpy as np
import torch

In [3]:
# prompt: tensor with first 4 number starting from 1 and another tensor with 4 numbers starting from 6

import numpy as np
import torch
# **Arithematic Opertions**
tensor_a = torch.arange(1,5)
tensor_b = torch.arange(6,10)
print(tensor_a)
print(tensor_b)


tensor([1, 2, 3, 4])
tensor([6, 7, 8, 9])


In [4]:
#Addition
tensor_a + tensor_b

tensor([ 7,  9, 11, 13])

In [6]:
#addition with long hand (funtion)
torch.add(tensor_a,tensor_b)

tensor([ 7,  9, 11, 13])

In [7]:
#Subtract
tensor_b - tensor_a

tensor([5, 5, 5, 5])

In [9]:
torch.sub(tensor_b,tensor_a)

tensor([5, 5, 5, 5])

In [11]:
#Multiplication
tensor_a * tensor_b

tensor([ 6, 14, 24, 36])

In [12]:
torch.mul(tensor_a,tensor_b)

tensor([ 6, 14, 24, 36])

In [13]:
#Division
tensor_b / tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500])

In [14]:
torch.div(tensor_b,tensor_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500])

In [15]:
#Modular
tensor_b % tensor_a
#long hand
torch.remainder(tensor_b,tensor_a)

tensor([0, 1, 2, 1])

In [16]:
#Exponents
tensor_a ** tensor_b
#long hand
torch.pow(tensor_a,tensor_b)

tensor([     1,    128,   6561, 262144])

In [17]:
#Another way to write longhand
tensor_a.add_(tensor_b)

tensor([ 7,  9, 11, 13])

In [18]:
#Reasignment
tensor_a + tensor_b

tensor([13, 16, 19, 22])

In [19]:
tensor_a

tensor([ 7,  9, 11, 13])

In [20]:
tensor_a += tensor_b

In [21]:
tensor_a

tensor([13, 16, 19, 22])

In [22]:
tensor_a.add_(tensor_b)

tensor([19, 23, 27, 31])