<a href="https://colab.research.google.com/github/kaamiawan007/pytorch/blob/main/pytorch_2nd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
#!pip list

In [2]:
# prompt: generate a basic list

my_list = [1, 2, 3, 4, 5]


In [3]:
# prompt: Generate a Numpy array

import numpy as np

my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


In [4]:
# prompt: Generate a basic tensor

my_tensor = torch.tensor(my_array)
print(my_tensor)


tensor([1, 2, 3, 4, 5])


In [5]:
# prompt: Generate a the type of all above codes

import torch
import numpy as np
#!pip list

my_list = [1, 2, 3, 4, 5]
print(type(my_list))


my_array = np.array(my_list)
print(type(my_array))


my_tensor = torch.tensor(my_array)
print(type(my_tensor))


<class 'list'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [6]:
# prompt: Generate 3d tensor

import torch
import numpy as np

# Create a 3D tensor directly from a nested list
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)

# Create a 3D tensor from a NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_3d_from_array = torch.tensor(array_3d)
print(tensor_3d_from_array)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [8]:
# Tensor is created form Numpy array that's why it's type is int64
# By Default the type of tensor is int32
tensor_3d_from_array.dtype

torch.int64

In [9]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
my_torch = my_torch.reshape(2,5)
print(my_torch)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [19]:
my_torch2 = torch.arange(1,30,3)
print(my_torch2)

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])


In [23]:
my_torch2 = my_torch2.reshape(5,-1)
print(my_torch2)

tensor([[ 1,  4],
        [ 7, 10],
        [13, 16],
        [19, 22],
        [25, 28]])


In [24]:
my_torch3 = torch.arange(10)
print(my_torch3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [25]:
my_torch4 = my_torch3.view(2,5)
print(my_torch4)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [4]:
#with Reshpae and view can be updated
my_torch5 = torch.arange(10)
print(my_torch5)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [28]:
my_torch6 = my_torch5.reshape(2,5)
print(my_torch6)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [5]:
my_torch5[1] = 4141
print(my_torch5)

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])


In [30]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [6]:
my_torch7 = my_torch5.reshape(2,5)
print(my_torch7)

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [7]:
my_torch7 = torch.arange(10)
print(my_torch7)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
my_torch7[7] = 41
print(my_torch7)

tensor([ 0,  1,  2,  3,  4,  5,  6, 41,  8,  9])


In [10]:
my_torch7 [7]

tensor(41)

In [11]:
my_torch8 = my_torch7.reshape(5,2)
print(my_torch8)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6, 41],
        [ 8,  9]])


In [12]:
# prompt: Generate code to slice column 1

# Slice column 1 (index 0)
column_1 = my_torch8[:, 0]
print(column_1)


tensor([0, 2, 4, 6, 8])


In [13]:
column_2 = my_torch8[:, 1]
print(column_2)

tensor([ 1,  3,  5, 41,  9])


In [14]:
#Retrun a column
my_torch8[:, 1:]

tensor([[ 1],
        [ 3],
        [ 5],
        [41],
        [ 9]])